### ISSUE TITLE
Could not find gem 'paperclip-i18n' in any of the gem sources listed in your Gemfile or available on this machine.

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/paperclip-i18n#11]
I tried to install the gem, but am unable to via Bundler.

**Comment by tute** [comment]
Released v4.3, which should work for either version of paperclip: https://rubygems.org/gems/paperclip-i18n. Anyhow, it might be easier for you to copy into your `config/locales/` repository the appropriate file. Now it's your choice. :)

Thanks for reporting!
