### ISSUE TITLE
Can't find gem 

### ISSUE THREAD

**Issue by Xosmond** [thoughtbot/paperclip-i18n#3]
Says that not found gem paperclip-i18n:
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'paperclip-i18n' in any of the gem
sources listed in your Gemfile or available on this
machine.

**Comment by tute** [comment]
Indeed it's not published yet. This is dependent on the stalled paperclip issue: https://github.com/thoughtbot/paperclip/issues/2049.

**Comment by tute** [comment]
Meanwhile, you can point bundler to github, or just copy the yml into your project. Thanks for reporting!

**Comment by Xosmond** [comment]
Oh i understand, thanks for reply.
